# Docker configuration backend
providers:
  providersThrottleDuration: 2s
  file:
    directory: ./traefik/dynamic/
    watch: true
log:
  level: DEBUG

api:
  insecure: true

entryPoints:
  web:
    address: :8000
  http:
    address: :8001
  traefik:
    address: :8080
