# Docker configuration backend
providers:
  providersThrottleDuration: 2s
  file:
    directory: ./traefik/dynamic/
    watch: true
log:
  level: DEBUG

api:
  insecure: false

entryPoints:
  web:
    address: :80
  # enable in case you need the dashboard
  # traefik:
  #   address: :8080
